//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/purposeVisibilitySchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPurposeVisibilitySchemaTokens,
    HD_PURPOSE_VISIBILITY_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdPurposeVisibilitySchema::GetGuideVisibility() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPurposeVisibilitySchemaTokens->guideVisibility);
}

HdTokenDataSourceHandle
HdPurposeVisibilitySchema::GetProxyVisibility() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPurposeVisibilitySchemaTokens->proxyVisibility);
}

HdTokenDataSourceHandle
HdPurposeVisibilitySchema::GetRenderVisibility() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPurposeVisibilitySchemaTokens->renderVisibility);
}

/*static*/
HdContainerDataSourceHandle
HdPurposeVisibilitySchema::BuildRetained(
        const HdTokenDataSourceHandle &guideVisibility,
        const HdTokenDataSourceHandle &proxyVisibility,
        const HdTokenDataSourceHandle &renderVisibility
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (guideVisibility) {
        _names[_count] = HdPurposeVisibilitySchemaTokens->guideVisibility;
        _values[_count++] = guideVisibility;
    }

    if (proxyVisibility) {
        _names[_count] = HdPurposeVisibilitySchemaTokens->proxyVisibility;
        _values[_count++] = proxyVisibility;
    }

    if (renderVisibility) {
        _names[_count] = HdPurposeVisibilitySchemaTokens->renderVisibility;
        _values[_count++] = renderVisibility;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPurposeVisibilitySchema::Builder &
HdPurposeVisibilitySchema::Builder::SetGuideVisibility(
    const HdTokenDataSourceHandle &guideVisibility)
{
    _guideVisibility = guideVisibility;
    return *this;
}

HdPurposeVisibilitySchema::Builder &
HdPurposeVisibilitySchema::Builder::SetProxyVisibility(
    const HdTokenDataSourceHandle &proxyVisibility)
{
    _proxyVisibility = proxyVisibility;
    return *this;
}

HdPurposeVisibilitySchema::Builder &
HdPurposeVisibilitySchema::Builder::SetRenderVisibility(
    const HdTokenDataSourceHandle &renderVisibility)
{
    _renderVisibility = renderVisibility;
    return *this;
}

HdContainerDataSourceHandle
HdPurposeVisibilitySchema::Builder::Build()
{
    return HdPurposeVisibilitySchema::BuildRetained(
        _guideVisibility,
        _proxyVisibility,
        _renderVisibility
    );
}

/*static*/
HdPurposeVisibilitySchema
HdPurposeVisibilitySchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPurposeVisibilitySchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPurposeVisibilitySchemaTokens->purposeVisibility))
        : nullptr);
}

/*static*/
const TfToken &
HdPurposeVisibilitySchema::GetSchemaToken()
{
    return HdPurposeVisibilitySchemaTokens->purposeVisibility;
}

/*static*/
const HdDataSourceLocator &
HdPurposeVisibilitySchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE