#!/pxrpythonsubst
#
# Copyright 2024 NVIDIA Corporation
# SPDX-License-Identifier: Apache-2.0

"""Tests for the usdsolidtessellate CLI and tessellation correctness.

Runs the CLI against the 10 fixtures in fixtures/ and checks vertex
counts, winding (signed volume), and mesh properties.

Vertex-count baselines were validated to be identical on two independent
configurations: Linux GCC 13 + OCCT 7.8.1 and Windows MSVC (VS 2026) +
OCCT 8.0.0 (vcpkg). Curved-surface counts are deterministic for a given
OCCT meshing algorithm; if a future OCCT changes them, update the
baselines deliberately.
"""

from pxr import Usd, UsdGeom
import math
import os
import subprocess
import tempfile
import unittest


# Expected total vertex counts per fixture (regression baseline).
#
# The hole/pocket fixtures (testPlaneWithHole, testCubeWithHole,
# testFilletedCubeWithHole, testDepressedPlane) are generated by the OCCT
# exporter (tools/brepExport.cpp) so their trim pcurves are guaranteed
# consistent with each face's surface parameterization. Their counts were
# re-validated on Linux GCC 13 + OCCT 7.8.1 after the curveUv (pcurve)
# trimming path landed; re-check on Windows + OCCT 8.0.0 if that toolchain
# changes the meshing.
EXPECTED_VERT_COUNTS = {
    # testCylinder was regenerated as an EDGED NURBS solid (OCCT exporter,
    # seam+rim edges, proposal rule 424) replacing the earlier edgeless
    # single-periodic-NURBS form; its meshing density changed, so it was
    # re-baselined (Linux GCC 13 + OCCT 7.8.1).
    #
    # testCone was regenerated as the analytic (BrepSurfaceConeAPI) solid to
    # remove the two degenerate apex edges of the earlier edged-NURBS form
    # (proposal rule 381: no degenerate geometry). Two seam-meridian edges + a
    # base rim, the apex is a converging vertex (no zero-length edge); the
    # hdOcct builder closes the apex via the parametric pole-closure fallback.
    # Re-baselined 281 -> 104 (Linux GCC 13 + OCCT 7.8.1); meshes to signed
    # volume +256.8 vs true (1/3)*pi*5^2*10 = 261.8 (chord deflection on the
    # curved lateral surface + apex fan).
    'testCone.usda': 104,
    'testCube.usda': 24,
    'testCubeWithHole.usda': 148,
    'testCylinder.usda': 124,
    'testDepressedPlane.usda': 122,
    # testDepressedPlaneSeamSplit is the SAME depressed plane authored under the
    # proposed producer convention "split full-period periodic faces at the
    # seam": the full-period (u=0..2pi) cylindrical well wall is split at the
    # seam and at u=pi into two half-period wall faces. A reader that
    # mis-tessellates full-period faces (e.g. SMLib on the unsplit twin) can then
    # verify the convention with zero reader changes; hdOcct (full-period
    # capable) meshes the split form to the SAME trimmed areas as the unsplit
    # twin (see test_DepressedPlaneSeamSplit_Pocket) -- proving the split
    # encoding does not regress a full-period consumer. The extra u=pi seam edges
    # + two half-walls raise the vert count (122 -> 136); re-baselined Linux GCC
    # 13 + OCCT 7.8.1.
    'testDepressedPlaneSeamSplit.usda': 136,
    # testFilletedCube was regenerated degenerate-edge-free: the earlier form
    # closed each of the 8 cube-corner spherical blends with a zero-length
    # corner edge (all control vertices equal), which BrepArrayDegenerateEdges
    # (BA.230) flags. The corners are now converging vertices (proposal rule
    # 381 / rule 428); the corner blend patches mesh through the builder's NURBS
    # pcurve path. Re-baselined 512 -> 496 (Linux GCC 13 + OCCT 7.8.1); signed
    # volume +974.9 (box 10^3 minus the 12 edge + 8 corner fillet volumes).
    'testFilletedCube.usda': 496,
    'testFilletedCubeWithHole.usda': 620,
    'testPlane.usda': 4,
    'testPlaneWithHole.usda': 33,
    # testSphere was regenerated as the analytic (BrepSurfaceSphereAPI) solid to
    # remove the degenerate pole edges of the earlier edged-NURBS form (proposal
    # rule 381: no degenerate geometry). Two seam-meridian edges, poles are
    # converging vertices, no zero-length edges; re-baselined (Linux GCC 13 +
    # OCCT 7.8.1). Meshes slightly under the true 4/3*pi*5^3 = 523.6 (chord
    # deflection on the curved surface).
    'testSphere.usda': 306,
    'testTwoBoxes.usda': 48,
    'testProducerCube.usda': 24,
    # testRealToleranceCylinder is a real-CAD lock pin sliced verbatim from the
    # toolbox STEP (occ_3 in testToolbox.usda): a short capped cylinder (r=1.9,
    # L=90) as a void+solid region pair, no pcurves. It carries REAL production
    # tolerances -- radius 1.9000000000000035, rim endpoints y=2.33e-16 -- the
    # imperfection class that failed 519/581 toolbox faces before the
    # shared-vertex wire-assembly fix (brepBuilder.cpp 1e0ab9f0d). The two
    # half-cylinder walls + two caps close only because the builder welds rim
    # vertices by intersectTol3d, not exact match. Re-baselined Linux GCC 13 +
    # OCCT 7.8.1.
    'testRealToleranceCylinder.usda': 108,
    # testAnalyticPlaneWithHole is an analytic plane (BrepSurfacePlaneAPI) with a
    # full-circle analytic hole (BrepCurve3dCircleAPI, u=0..2pi), NO pcurves --
    # the BRepCheck_BadOrientationOfSubshape class fixed in brepBuilder.cpp
    # commit ab344ef05. Distinct from testPlaneWithHole (NURBS-surfaced, WITH
    # pcurves). 20x20 sheet centered at origin minus a r=3 hole. Re-baselined
    # Linux GCC 13 + OCCT 7.8.1.
    'testAnalyticPlaneWithHole.usda': 30,
    # testFullPeriodTorus is one torus face spanning the full major period
    # u=[0,2pi] with a partial minor band v=[0,pi] (R=5, r=2) -- the full-period
    # torus residual class (6 such faces in the toolbox). Its u-boundary is a
    # seam, not a wire, so it renders via the parametric face:range fallback (as
    # testFullSphere does). The fallback is CORRECT here (meshed area matches the
    # analytic band ~197.39), so it is a normal assertion. Re-baselined Linux GCC
    # 13 + OCCT 7.8.1.
    'testFullPeriodTorus.usda': 547,
    # testFullPeriodSphereBand is one sphere face spanning the full major period
    # u=[0,2pi] with a latitude band v=[-pi/4,pi/4] (NOT pole-touching), R=5 --
    # the full-period sphere-band residual, distinct from the pole-touching
    # testFullSphere. Renders via the parametric face:range fallback; the fallback
    # is CORRECT here (meshed area matches the analytic band ~222.14). Re-baselined
    # Linux GCC 13 + OCCT 7.8.1.
    'testFullPeriodSphereBand.usda': 179,
    # Seam-split twins of the two full-period residuals: the full major sweep is
    # split at u=0/2pi and u=pi into two wire-bounded HALF-period faces (the
    # producer convention landed for the depressed-plane wall in
    # testDepressedPlaneSeamSplit). A full-period-limited reader can consume these
    # with no reader changes; hdOcct meshes them to the SAME band area as the
    # unsplit twins (asserted split==unsplit). Re-baselined Linux GCC 13 + OCCT
    # 7.8.1.
    'testFullPeriodTorusSeamSplit.usda': 562,
    'testFullPeriodSphereBandSeamSplit.usda': 196,
    # testMixedSurfaces is a capped cylinder (r=3, z in [0,5]) whose two lateral
    # walls are analytic half-cylinders (BrepSurfaceCylinderAPI) and whose two
    # caps are NURBS planar patches (BrepSurfaceNurbAPI), with the
    # face:surfaceType families INTERLEAVED [nurb, cylinder, nurb, cylinder]. It
    # pins the mixed-family surface-array PACKING: the builder indexes each
    # per-family array (surface:nurb:*, surface:cylinder:*) by a face's ordinal
    # WITHIN its family, so a reader that walks the NURBS arrays with a single
    # all-NURBS cursor (the class that failed a real-CAD prim with 9 NURBS among
    # 581 analytic faces in the SMLib reader) grabs the wrong slot and mis-builds
    # the solid. Correct packing meshes both walls as r=3 half-cylinders and both
    # caps as z=0/z=5 patches -> this deterministic vert count, a positive signed
    # volume, and an exact [-3,3]x[-3,3]x[0,5] bbox. Re-baselined 64 -> 108 when
    # the derive-trim gate widened to single-loop NURBS faces: the two NURBS caps
    # now wire-trim to r=3 disks (was full 6x6 squares) and the solid meshes
    # watertight at signed volume ~140 (~pi*9*5); see test_MixedSurfaces_CapsTrimmed
    # (now a normal passing assertion). The fixture's two cap faceuse:orientationType
    # entries were also corrected (they were authored for a +Z cap normal, but the
    # cap CP ordering gives -Z, so both caps meshed inward). Re-baselined Linux GCC
    # 13 + OCCT 7.8.1.
    'testMixedSurfaces.usda': 108,
    # testMixedCurvesWithPcurves is one NURBS planar sheet whose single outer
    # trim loop mixes CURVE families with AUTHORED pcurves: two lines
    # (BrepCurve3dLineAPI), one NURBS edge (BrepCurve3dNurbAPI), one circle arc
    # (BrepCurve3dCircleAPI). It exercises the hasTrimCurves (pcurve) branch with
    # analytic 3D edges present alongside a NURBS edge -- the mixed edge-family
    # packing whose per-edgeuse fallback (edges[] built NURBS-only) would drop an
    # analytic edge if a pcurve failed (documented in brepBuilder.cpp; not
    # triggered here because every pcurve is valid). Region = rectangle
    # [0,4]x[0,3] plus a left semicircular bulge; trimmed area ~15.53.
    # Re-baselined Linux GCC 13 + OCCT 7.8.1.
    'testMixedCurvesWithPcurves.usda': 18,
}

PRIM_PATHS = {
    'testCone.usda': '/World/Cone',
    'testCube.usda': '/World/Cube',
    'testCubeWithHole.usda': '/World/CubeWithHole',
    'testCylinder.usda': '/World/Cylinder',
    'testDepressedPlane.usda': '/World/DepressedPlane',
    'testDepressedPlaneSeamSplit.usda': '/World/DepressedPlane',
    'testFilletedCube.usda': '/World/FilletedCube',
    'testFilletedCubeWithHole.usda': '/World/FilletedCubeWithHole',
    'testPlane.usda': '/World/Plane',
    'testPlaneWithHole.usda': '/World/PlaneWithHole',
    'testSphere.usda': '/World/Sphere',
    'testTwoBoxes.usda': '/World/TwoBoxes',
    'testAnalyticPlane.usda': '/World/AnPlane',
    'testAnalyticCylinder.usda': '/World/AnalyticCyl',
    'testAnalyticCone.usda': '/World/AnCone',
    'testAnalyticSphere.usda': '/World/AnSphere',
    'testAnalyticTorus.usda': '/World/AnTorus',
    'testAnalyticCylinderEdges.usda': '/World/CylEdge',
    'testAnalyticConeEdges.usda': '/World/ConeEdge',
    'testFullSphere.usda': '/World/FullSphere',
    'testProducerCube.usda': '/World/Cube',
    'testVoidOnlySphere.usda': '/World/VoidSphere',
    'testRealToleranceCylinder.usda': '/World/RealPin',
    'testAnalyticPlaneWithHole.usda': '/World/AnPlaneHole',
    'testFullPeriodTorus.usda': '/World/FullTorus',
    'testFullPeriodTorusSeamSplit.usda': '/World/FullTorus',
    'testFullPeriodSphereBand.usda': '/World/SphereBand',
    'testFullPeriodSphereBandSeamSplit.usda': '/World/SphereBand',
    'testMixedSurfaces.usda': '/World/MixedSurfaces',
    'testMixedCurvesWithPcurves.usda': '/World/MixedCurves',
    'testForcedFallbackCone.usda': '/World/FallbackCone',
    'testEllipseXrLtYrArc.usda': '/World/EllipseSector',
}

# Closed solids: signed volume must be positive (outward winding).
CLOSED_SOLIDS = [
    'testCone.usda',
    'testCube.usda',
    'testCubeWithHole.usda',
    'testCylinder.usda',
    'testFilletedCube.usda',
    'testFilletedCubeWithHole.usda',
    'testSphere.usda',
    'testTwoBoxes.usda',
    'testProducerCube.usda',
]

# Analytic-surface fixtures -> (expected meshed area, absolute tolerance).
#
# These exercise the analytic surface readers: each face is built from its
# schema parameters (origin/axis/refDirection + radius/semiAngle/...) rather
# than NURBS control points. The five surface types use the authored curveUv
# (pcurve) trimming path; the *Edges fixtures additionally exercise the
# analytic 3D-edge path (analytic surface trimmed by analytic circle/line
# curves with no authored curveUv). Areas are geometric and independent of
# the OCCT meshing algorithm; curved surfaces mesh slightly under their true
# area (chord-height deflection), so the tolerance permits a small undershoot.
ANALYTIC_AREA_FIXTURES = {
    'testAnalyticPlane.usda':         (12.0, 0.5),
    'testAnalyticCylinder.usda':      (2.0 * math.pi * 3.0 * 5.0, 2.0),
    'testAnalyticCone.usda':          (25.28, 1.0),
    'testAnalyticSphere.usda':        (59.98, 2.0),
    'testAnalyticTorus.usda':         (203.22, 6.0),
    'testAnalyticCylinderEdges.usda': (70.686, 2.5),
    'testAnalyticConeEdges.usda':     (25.28, 1.5),
    # Full sphere (r=2) encoded as a producer does it: one face whose only edge is
    # a pole-to-pole meridian SEAM, no curveUv, face:range = the full sphere. The
    # 3D-edge wire cannot bound a pole-enclosing patch, so this exercises the
    # parametric face:range fallback (OCCT adds the seam + degenerate pole edges).
    'testFullSphere.usda':            (4.0 * math.pi * 4.0, 2.0),
    # Full-period torus band, u=[0,2pi] x v=[0,pi], R=5 r=2 -> the u-seam face
    # renders via the parametric face:range fallback. True band area
    # 2*pi*r*(R*(v1-v0) + r*(sin v1 - sin v0)) with v=[0,pi] => ~197.39.
    'testFullPeriodTorus.usda':       (197.392, 3.0),
    # Full-period sphere band, u=[0,2pi] x v=[-pi/4,pi/4], R=5 (not pole-touching)
    # -> parametric face:range fallback. True band area 2*pi*R^2*(sin v1 - sin v0)
    # = 2*pi*25*sqrt(2) => ~222.14.
    'testFullPeriodSphereBand.usda':  (222.144, 4.0),
}


def _get_fixtures_dir():
    """Fixtures live next to the installed test (ctest) or the script."""
    for base in (os.getcwd(),
                 os.path.dirname(os.path.abspath(__file__))):
        d = os.path.join(base, 'fixtures')
        if os.path.isdir(d):
            return d
        d = os.path.join(base, 'testUsdSolidTessellation', 'fixtures')
        if os.path.isdir(d):
            return d
    raise RuntimeError("fixtures directory not found")


def _get_tessellator_bin():
    """Find the usdsolidtessellate binary."""
    env_bin = os.environ.get('USDSOLIDTESSELLATE_BIN')
    if env_bin and os.path.isfile(env_bin):
        return env_bin
    from shutil import which
    path_bin = which('usdsolidtessellate')
    if path_bin:
        return path_bin
    return 'usdsolidtessellate'


def _run_tessellator(input_path, output_path, prim_path):
    result = subprocess.run(
        [_get_tessellator_bin(), input_path, output_path, prim_path],
        capture_output=True, text=True, timeout=120)
    return result.returncode, result.stdout, result.stderr


def _tessellate_fixture(fixture_name):
    input_path = os.path.join(_get_fixtures_dir(), fixture_name)
    prim_path = PRIM_PATHS[fixture_name]
    fd, output_path = tempfile.mkstemp(suffix='.usda')
    os.close(fd)
    rc, stdout, stderr = _run_tessellator(input_path, output_path, prim_path)
    if rc != 0:
        os.unlink(output_path)
        raise RuntimeError(
            f"Tessellation failed for {fixture_name}: {stdout} {stderr}")
    stage = Usd.Stage.Open(output_path)
    os.unlink(output_path)
    return stage


def _meshes(stage):
    return [UsdGeom.Mesh(p) for p in stage.TraverseAll()
            if p.GetTypeName() == 'Mesh']


def _signed_volume(points, face_vertex_counts, face_vertex_indices):
    """Signed volume of a triangle mesh (positive = outward winding)."""
    volume = 0.0
    idx = 0
    for count in face_vertex_counts:
        if count != 3:
            idx += count
            continue
        v0 = points[face_vertex_indices[idx]]
        v1 = points[face_vertex_indices[idx + 1]]
        v2 = points[face_vertex_indices[idx + 2]]
        volume += (v0[0] * (v1[1] * v2[2] - v1[2] * v2[1]) +
                   v0[1] * (v1[2] * v2[0] - v1[0] * v2[2]) +
                   v0[2] * (v1[0] * v2[1] - v1[1] * v2[0]))
        idx += count
    return volume / 6.0


class TestTessellationVertexCounts(unittest.TestCase):
    """Each fixture produces the validated vertex count (regression)."""

    def _check_fixture(self, fixture_name):
        stage = _tessellate_fixture(fixture_name)
        total_verts = sum(len(m.GetPointsAttr().Get())
                          for m in _meshes(stage))
        expected = EXPECTED_VERT_COUNTS[fixture_name]
        self.assertEqual(total_verts, expected,
                         f"{fixture_name}: expected {expected} verts, "
                         f"got {total_verts}")

    def test_Cube(self):
        self._check_fixture('testCube.usda')

    def test_Sphere(self):
        self._check_fixture('testSphere.usda')

    def test_Cylinder(self):
        self._check_fixture('testCylinder.usda')

    def test_Cone(self):
        self._check_fixture('testCone.usda')

    def test_CubeWithHole(self):
        self._check_fixture('testCubeWithHole.usda')

    def test_DepressedPlane(self):
        self._check_fixture('testDepressedPlane.usda')

    def test_DepressedPlaneSeamSplit(self):
        self._check_fixture('testDepressedPlaneSeamSplit.usda')

    def test_FilletedCube(self):
        self._check_fixture('testFilletedCube.usda')

    def test_FilletedCubeWithHole(self):
        self._check_fixture('testFilletedCubeWithHole.usda')

    def test_Plane(self):
        self._check_fixture('testPlane.usda')

    def test_PlaneWithHole(self):
        self._check_fixture('testPlaneWithHole.usda')

    def test_TwoBoxes(self):
        self._check_fixture('testTwoBoxes.usda')

    def test_ProducerCube(self):
        self._check_fixture('testProducerCube.usda')


class TestTessellationWindingOrder(unittest.TestCase):
    """Signed volume is positive for closed solids.

    Winding and normals are driven by the authored faceuse:orientationType.
    For the hand-authored fixtures (single solidRegion shell, interleaved
    faceuses) the first faceuse of each face's pair is the outward side; for
    producer fixtures (voidRegion + solidRegion shells, faceuses grouped by
    shell with faceuse:faceIndex) the voidRegion faceuse is the outward side.
    Either way outward orientation is exact, not heuristic.
    """

    def _check_winding(self, fixture_name):
        stage = _tessellate_fixture(fixture_name)
        meshes = _meshes(stage)
        self.assertTrue(meshes, f"{fixture_name}: no meshes produced")
        for mesh in meshes:
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertGreater(vol, 0,
                               f"{fixture_name}: signed volume {vol} <= 0 "
                               f"(bad winding)")

    def test_Cube(self):
        self._check_winding('testCube.usda')

    def test_Sphere(self):
        self._check_winding('testSphere.usda')

    def test_Cylinder(self):
        self._check_winding('testCylinder.usda')

    def test_Cone(self):
        self._check_winding('testCone.usda')

    def test_CubeWithHole(self):
        self._check_winding('testCubeWithHole.usda')

    def test_TwoBoxes(self):
        self._check_winding('testTwoBoxes.usda')

    def test_ProducerCube(self):
        # Producer radial-edge layout (voidRegion + solidRegion, faceuses
        # grouped by shell): the 10x10x10 box must keep outward winding AND its
        # full volume. The legacy 2*fi orientation lookup straddles the two
        # shells here and mis-orients half the faces, collapsing the signed
        # volume toward zero -- so assert the magnitude, not just the sign.
        stage = _tessellate_fixture('testProducerCube.usda')
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertAlmostEqual(
                vol, 1000.0, delta=1.0,
                msg=f"testProducerCube: signed volume {vol} != 1000 "
                    f"(orientation/closure error)")

    def test_VoidOnlySphere(self):
        # Void-only body (voidRegion, no solidRegion) whose interleaved coedge
        # pair is ordered ("opposite","same"). The fixed faceuse[2*fi] lookup
        # reads "opposite" and flips the whole sphere inward; the content-based
        # pick (layout C) keeps it outward. Expect a positive, sphere-sized
        # signed volume (4/3*pi*2^3 ~= 33.5, meshed slightly under).
        stage = _tessellate_fixture('testVoidOnlySphere.usda')
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertGreater(
                vol, 20.0,
                msg=f"testVoidOnlySphere: signed volume {vol} -- expected "
                    f"~33.5 outward; <=0 means the layout-C void-only "
                    f"orientation regressed (flipped inward)")


class TestTessellationMeshProperties(unittest.TestCase):
    """Output meshes have correct properties."""

    def test_NormalsPresent(self):
        stage = _tessellate_fixture('testSphere.usda')
        for mesh in _meshes(stage):
            normals = mesh.GetNormalsAttr().Get()
            points = mesh.GetPointsAttr().Get()
            self.assertIsNotNone(normals)
            self.assertEqual(len(normals), len(points))

    def test_NormalsUnitLength(self):
        stage = _tessellate_fixture('testCube.usda')
        for mesh in _meshes(stage):
            for n in mesh.GetNormalsAttr().Get():
                length = math.sqrt(n[0]**2 + n[1]**2 + n[2]**2)
                self.assertAlmostEqual(length, 1.0, places=4)

    def test_SubdivisionSchemeNone(self):
        stage = _tessellate_fixture('testCube.usda')
        for mesh in _meshes(stage):
            self.assertEqual(mesh.GetSubdivisionSchemeAttr().Get(), 'none')

    def test_FaceCountsNonZero(self):
        for fixture_name in EXPECTED_VERT_COUNTS:
            stage = _tessellate_fixture(fixture_name)
            total_faces = sum(len(m.GetFaceVertexCountsAttr().Get())
                              for m in _meshes(stage))
            self.assertGreater(total_faces, 0,
                               f"{fixture_name}: no faces produced")


def _planar_area_at_z(stage, z, tol=1e-4):
    """Sum of triangle areas whose three vertices all lie on plane Z=z."""
    area = 0.0
    for mesh in _meshes(stage):
        points = mesh.GetPointsAttr().Get()
        fvc = mesh.GetFaceVertexCountsAttr().Get()
        fvi = mesh.GetFaceVertexIndicesAttr().Get()
        idx = 0
        for count in fvc:
            tri = [points[fvi[idx + k]] for k in range(count)]
            idx += count
            if count != 3 or not all(abs(p[2] - z) < tol for p in tri):
                continue
            ux, uy, uz = (tri[1][0] - tri[0][0], tri[1][1] - tri[0][1],
                          tri[1][2] - tri[0][2])
            vx, vy, vz = (tri[2][0] - tri[0][0], tri[2][1] - tri[0][1],
                          tri[2][2] - tri[0][2])
            cx, cy, cz = (uy * vz - uz * vy, uz * vx - ux * vz,
                          ux * vy - uy * vx)
            area += 0.5 * math.sqrt(cx * cx + cy * cy + cz * cz)
    return area


def _mesh_bbox(stage):
    """Axis-aligned bbox of all mesh points: ((xmin,ymin,zmin),(xmax,...))."""
    xs, ys, zs = [], [], []
    for mesh in _meshes(stage):
        for p in mesh.GetPointsAttr().Get():
            xs.append(p[0]); ys.append(p[1]); zs.append(p[2])
    if not xs:
        return None
    return ((min(xs), min(ys), min(zs)), (max(xs), max(ys), max(zs)))


def _total_surface_area(stage):
    area = 0.0
    for mesh in _meshes(stage):
        points = mesh.GetPointsAttr().Get()
        fvc = mesh.GetFaceVertexCountsAttr().Get()
        fvi = mesh.GetFaceVertexIndicesAttr().Get()
        idx = 0
        for count in fvc:
            if count == 3:
                a, b, c = (points[fvi[idx + k]] for k in range(3))
                ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
                vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
                cx, cy, cz = (uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx)
                area += 0.5 * math.sqrt(cx*cx + cy*cy + cz*cz)
            idx += count
    return area


class TestTrimmedFaceArea(unittest.TestCase):
    """Multi-loop (hole/pocket) faces mesh their full trimmed area.

    Regression for the curveUv (pcurve) trimming path. Before it landed,
    faces trimmed via projected 3D-edge wires meshed to a small fraction
    of their true area (testCubeWithHole's punctured face: ~12.5 of ~71.7).
    Now each loop edge is built directly from its authored 2D pcurve, so
    the trimmed area is exact. Geometry-based (OCCT-meshing-independent).
    """

    def test_PlaneWithHole_FullArea(self):
        # 20x20 sheet minus a r=3 hole.
        stage = _tessellate_fixture('testPlaneWithHole.usda')
        expected = 400.0 - math.pi * 9.0
        area = _total_surface_area(stage)
        self.assertAlmostEqual(area, expected, delta=2.0,
                               msg=f"sheet area {area:.2f} != {expected:.2f}")

    def test_AnalyticPlaneWithHole_FullArea(self):
        # Analytic plane trimmed by an outer square + a full-circle analytic hole
        # (no pcurves): 20x20 sheet minus a r=3 hole. A hole-orientation failure
        # (the BadOrientationOfSubshape class fixed in ab344ef05) either rejects
        # the wire (empty/partial mesh) or fills the hole (area -> ~400); a clean
        # punch meshes to 400 - pi*9.
        stage = _tessellate_fixture('testAnalyticPlaneWithHole.usda')
        expected = 400.0 - math.pi * 9.0
        area = _total_surface_area(stage)
        self.assertAlmostEqual(area, expected, delta=2.0,
                               msg=f"analytic holed sheet area {area:.2f} != "
                                   f"{expected:.2f} (hole orientation?)")

    def test_CubeWithHole_PuncturedFaces(self):
        # Top (z=10) and bottom (z=0) faces are each 10x10 minus a r=3 hole.
        stage = _tessellate_fixture('testCubeWithHole.usda')
        expected = 100.0 - math.pi * 9.0
        for z in (0.0, 10.0):
            area = _planar_area_at_z(stage, z)
            self.assertAlmostEqual(
                area, expected, delta=1.0,
                msg=f"z={z} punctured face area {area:.2f} != {expected:.2f}")

    def test_DepressedPlane_Pocket(self):
        # 20x20 sheet with a r=3 cylindrical pocket of depth 5: the top must
        # be a real opening (zero meshed area inside the hole circle), and a
        # bottom cap must exist at z=-5.
        stage = _tessellate_fixture('testDepressedPlane.usda')
        top = _planar_area_at_z(stage, 0.0)
        bottom = _planar_area_at_z(stage, -5.0)
        self.assertAlmostEqual(top, 400.0 - math.pi * 9.0, delta=2.0,
                               msg=f"pocket top area {top:.2f}")
        self.assertAlmostEqual(bottom, math.pi * 9.0, delta=2.0,
                               msg=f"pocket bottom cap area {bottom:.2f}")

    def test_DepressedPlaneSeamSplit_Pocket(self):
        # Seam-split twin: the SAME depressed plane with the full-period well
        # wall split at the seam (u=0/2pi) and at u=pi into two half-period wall
        # faces. This asserts the split encoding meshes to the SAME trimmed areas
        # as the unsplit twin (test_DepressedPlane_Pocket) -- a permanent
        # split==unsplit equivalence gate on a full-period-capable consumer,
        # complementing the SMLib cross-kernel proof that the split form lets a
        # full-period-limited reader get exact numbers with no reader changes.
        stage = _tessellate_fixture('testDepressedPlaneSeamSplit.usda')
        top = _planar_area_at_z(stage, 0.0)
        bottom = _planar_area_at_z(stage, -5.0)
        self.assertAlmostEqual(top, 400.0 - math.pi * 9.0, delta=2.0,
                               msg=f"seam-split pocket top area {top:.2f}")
        self.assertAlmostEqual(bottom, math.pi * 9.0, delta=2.0,
                               msg=f"seam-split pocket bottom cap area {bottom:.2f}")


class TestSeamSplitEquivalence(unittest.TestCase):
    """Seam-split twins of the full-period torus/sphere-band mesh to the SAME
    band area as their unsplit full-period twins.

    The unsplit forms (testFullPeriodTorus, testFullPeriodSphereBand) render via
    the parametric face:range fallback because a full major sweep u=[0,2pi] has a
    seam, not a bounding wire. The split twins author the identical geometry as
    two wire-bounded half-period faces (u=[0,pi] and [pi,2pi]) under the producer
    convention "split full-period periodic faces at the seam" -- so a reader that
    cannot tessellate a full-period seam face gets exact numbers with zero reader
    changes, while a full-period-capable consumer (hdOcct) proves the split
    encoding does not regress it. This asserts split area == unsplit area (both
    == the analytic band), extending the seam-split evidence beyond the depressed
    plane (test_DepressedPlaneSeamSplit_Pocket) to curved analytic surfaces.
    """

    def _assert_same_area(self, split_name, unsplit_name, delta=1.0):
        split_area = _total_surface_area(_tessellate_fixture(split_name))
        unsplit_area = _total_surface_area(_tessellate_fixture(unsplit_name))
        self.assertAlmostEqual(
            split_area, unsplit_area, delta=delta,
            msg=f"{split_name} area {split_area:.2f} != {unsplit_name} "
                f"area {unsplit_area:.2f} (split encoding changed the mesh)")

    def test_FullPeriodTorus_SeamSplitEquivalence(self):
        self._assert_same_area('testFullPeriodTorusSeamSplit.usda',
                               'testFullPeriodTorus.usda')

    def test_FullPeriodSphereBand_SeamSplitEquivalence(self):
        self._assert_same_area('testFullPeriodSphereBandSeamSplit.usda',
                               'testFullPeriodSphereBand.usda')


class TestRealToleranceWireClosure(unittest.TestCase):
    """A real-CAD part with production tolerances closes and meshes exactly.

    testRealToleranceCylinder is a lock pin sliced verbatim from the toolbox
    STEP (occ_3): a capped cylinder r=1.9, L=90 as a void+solid region pair with
    NO pcurves. Its rim endpoints carry real imperfection (y=2.326828918e-16
    where the model means 0; radius 1.9000000000000035). The two half-cylinder
    walls and the two planar caps meet at rim vertices that agree only to
    intersectTol3d, so the wire builder must weld by tolerance, not by exact
    coordinate match, to close each face's boundary. This is the class that
    failed 519/581 toolbox faces before the shared-vertex fix landed in
    brepBuilder.cpp (commit 1e0ab9f0d): without it the lateral walls fail wire
    assembly and drop out (area collapses to ~2*caps and volume falls far below
    pi*r^2*L). The asserts below pin the FIXED behavior -- full lateral area and
    a positive, cylinder-sized signed volume -- so a regression of that weld
    (or a reader that assembles wires by exact match) flips this test loudly.
    Geometry-based, independent of the OCCT meshing density.
    """

    def test_RealToleranceCylinder_ClosesAndMeshes(self):
        stage = _tessellate_fixture('testRealToleranceCylinder.usda')
        area = _total_surface_area(stage)
        # True total surface = lateral 2*pi*r*L + 2 caps pi*r^2 = ~1097.1;
        # the curved wall chord-undershoots slightly. A tolerance-weld failure
        # would drop the ~1074.4 lateral area, leaving only ~22.7 (the caps).
        self.assertGreater(area, 1000.0,
                           f"lateral walls missing: area {area:.2f} (expected "
                           f"~1097; ~23 means the tolerance weld failed)")
        self.assertAlmostEqual(area, 1097.1, delta=6.0,
                               msg=f"pin surface area {area:.2f} != ~1097.1")
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            # True pi*r^2*L = ~1020.7; positive => outward winding (void faceuse
            # outward). A wire-closure failure collapses this toward zero.
            self.assertAlmostEqual(
                vol, 1020.7, delta=12.0,
                msg=f"pin signed volume {vol:.2f} != ~1020.7 "
                    f"(<=0 or tiny means wire closure/winding regressed)")


class TestTessellationErrorHandling(unittest.TestCase):
    """Bad inputs return errors without crashing."""

    def test_NonexistentPrimPath(self):
        input_path = os.path.join(_get_fixtures_dir(), 'testCube.usda')
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, _, _ = _run_tessellator(input_path, output_path,
                                    '/World/DoesNotExist')
        if os.path.exists(output_path):
            os.unlink(output_path)
        self.assertNotEqual(rc, 0)

    def test_NonexistentInputFile(self):
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, _, _ = _run_tessellator('does_not_exist_xyz.usda',
                                    output_path, '/World/Cube')
        if os.path.exists(output_path):
            os.unlink(output_path)
        self.assertNotEqual(rc, 0)


# Pcurve-less ("derived-trim") twins: fixtures/derivedTrims/<name>NoPcurves.usda
# are generated from the originals by removing the five brep:curveUv:nurb:*
# arrays and dropping the BrepCurveUvNurbAPI schema, so face trims are DERIVED
# from the 3D edge curves at read time. brep:curveUv is optional per proposal
# #109 (the 3D edge curve is the model truth), so a conformant consumer must
# handle both encodings. These counts are the derived-trim tessellation (coarser
# than the authored-pcurve original for curved faces, identical for planar).
# See fixtures/derivedTrims/README.md.
PCURVELESS_TWIN_VERTS = {
    'testCubeNoPcurves.usda': 24,
    # Re-baselined 72 -> 124 when single-loop NURBS faces gained the derive-trim
    # route (brepBuilder attemptTrim widened to any face with boundary edges).
    # The four NURBS cylinder panels formerly fell back to their oversized
    # control-net bounds (signed volume +307.0, ~8% over the true pi*9*10 =
    # 282.7); wire-trimming them to the authored circle/line edges brings the
    # twin to +280.6 / area 244.24 -- matching its authored-pcurve sibling
    # testCylinder (+281.0 / 244.24, also 124 verts) to 3 sig figs. Geometry is
    # strictly better; the vert count now equals the pcurve original.
    'testCylinderNoPcurves.usda': 124,
    'testConeNoPcurves.usda': 106,
    'testFilletedCubeNoPcurves.usda': 512,
    'testCubeWithHoleNoPcurves.usda': 148,
    'testPlaneWithHoleNoPcurves.usda': 33,
    # Re-baselined 97 -> 214 with the widened derive-trim gate. The pocket's
    # single-loop NURBS faces formerly used oversized natural bounds (signed
    # volume -153.5, ~9% past the true pocket); wire-trimming them yields -136.8,
    # within 2.6% of the authored-pcurve original testDepressedPlane (-140.5),
    # i.e. closer to truth. The extra verts are the properly-subdivided pocket
    # walls. Geometry improved; count re-baselined deliberately.
    'testDepressedPlaneNoPcurves.usda': 214,
}


class TestPcurveLessTwins(unittest.TestCase):
    """Derived-trim twins tessellate correctly with no authored pcurves."""

    def _tessellate_twin(self, twin_name):
        input_path = os.path.join(_get_fixtures_dir(), 'derivedTrims', twin_name)
        stage_in = Usd.Stage.Open(input_path)
        prim = next(p for p in stage_in.Traverse()
                    if p.GetTypeName() == 'BrepArray')
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, so, se = _run_tessellator(input_path, output_path,
                                      prim.GetPath().pathString)
        if rc != 0:
            os.unlink(output_path)
            raise RuntimeError(f"{twin_name}: tessellation failed: {so} {se}")
        stage = Usd.Stage.Open(output_path)
        os.unlink(output_path)
        return stage

    def test_twins_tessellate(self):
        for twin, expected in PCURVELESS_TWIN_VERTS.items():
            with self.subTest(twin=twin):
                stage = self._tessellate_twin(twin)
                verts = sum(len(m.GetPointsAttr().Get())
                            for m in _meshes(stage))
                self.assertEqual(verts, expected,
                                 f"{twin}: expected {expected} verts, "
                                 f"got {verts}")

    @unittest.expectedFailure
    def test_twin_Sphere_rendersFull(self):
        # testSphere is authored as two seam-split half-lune faces; without
        # pcurves the meridian-only boundary wire cannot close a lune (the
        # degenerate pole/seam edges are absent per rule 381), so the twin
        # renders half a sphere. Expected failure: it flips to XPASS if the
        # pole/seam derive path is ever completed, prompting a baseline update.
        # A sphere authored as a single natural-bound face (testAnalyticSphere)
        # renders correctly pcurve-less. See fixtures/derivedTrims/README.md.
        stage = self._tessellate_twin('testSphereNoPcurves.usda')
        ys = [p[1] for m in _meshes(stage) for p in m.GetPointsAttr().Get()]
        span_y = (max(ys) - min(ys)) if ys else 0.0
        self.assertGreater(span_y, 9.0,
                           "sphere twin should span the full diameter")


class TestAnalyticSurfaceArea(unittest.TestCase):
    """Analytic surfaces tessellate to their exact geometric area.

    Each analytic surface type (plane, cylinder, cone, sphere, torus) is
    constructed from its schema parameters rather than from NURBS control
    points, and trimmed via the authored curveUv (pcurve) path. The *Edges
    fixtures additionally exercise the analytic 3D-edge path: an analytic
    surface trimmed by analytic circle/line curves with no authored curveUv,
    where each edge's pcurve is projected onto the surface. Areas are
    geometry-based and independent of the OCCT meshing algorithm.
    """

    def _check_area(self, fixture_name):
        expected, tol = ANALYTIC_AREA_FIXTURES[fixture_name]
        stage = _tessellate_fixture(fixture_name)
        area = _total_surface_area(stage)
        self.assertGreater(area, 0.0, f"{fixture_name}: empty mesh")
        self.assertAlmostEqual(
            area, expected, delta=tol,
            msg=f"{fixture_name}: area {area:.3f} != {expected:.3f}")

    def test_AnalyticPlane(self):
        self._check_area('testAnalyticPlane.usda')

    def test_AnalyticCylinder(self):
        self._check_area('testAnalyticCylinder.usda')

    def test_AnalyticCone(self):
        self._check_area('testAnalyticCone.usda')

    def test_AnalyticSphere(self):
        self._check_area('testAnalyticSphere.usda')

    def test_AnalyticTorus(self):
        self._check_area('testAnalyticTorus.usda')

    def test_AnalyticCylinderEdges(self):
        self._check_area('testAnalyticCylinderEdges.usda')

    def test_AnalyticConeEdges(self):
        self._check_area('testAnalyticConeEdges.usda')

    def test_FullSphere(self):
        # Pole-enclosing analytic face (full sphere via meridian seam, no
        # curveUv) -> parametric face:range fallback. Common in real CAD output.
        self._check_area('testFullSphere.usda')

    def test_FullPeriodTorus(self):
        # Full-period torus band (u=[0,2pi] seam face) -> parametric face:range
        # fallback. Pins the fallback as CORRECT: meshed area matches the analytic
        # band. A fix/regression of the full-period path moves the area here.
        self._check_area('testFullPeriodTorus.usda')

    def test_FullPeriodSphereBand(self):
        # Full-period sphere band (u=[0,2pi], non-pole-touching) -> parametric
        # face:range fallback. Distinct from testFullSphere (pole-touching). Pins
        # the fallback as CORRECT (meshed area matches the analytic band).
        self._check_area('testFullPeriodSphereBand.usda')


class TestMixedFamilyPacking(unittest.TestCase):
    """A single prim mixing analytic and NURBS SURFACE families packs correctly.

    testMixedSurfaces is a capped cylinder (r=3, z in [0,5]) whose two lateral
    walls are analytic half-cylinders (BrepSurfaceCylinderAPI) and whose two
    caps are NURBS planar patches (BrepSurfaceNurbAPI). The face:surfaceType
    families are INTERLEAVED [nurb, cylinder, nurb, cylinder], so the per-family
    surface arrays (surface:nurb:* holds the caps at family-ordinals 0,1;
    surface:cylinder:* holds the walls at ordinals 0,1) can only be resolved by
    indexing each face by its ordinal WITHIN its family. A consumer that walks
    the NURBS arrays with one all-NURBS positional cursor -- the packing class
    that broke a real-CAD prim carrying 9 NURBS among 581 analytic faces in the
    SMLib USD reader (with an intermittent access violation) -- reads the wall
    slot for the top cap and mis-builds the solid. Correct packing meshes both
    walls as r=3 half-cylinders and both caps at z=0/z=5: a positive signed
    volume and an exact [-3,3]x[-3,3]x[0,5] bbox. Geometry/packing-based; the
    vert-count regression is pinned in EXPECTED_VERT_COUNTS.
    """

    def test_MixedSurfaces_Packing(self):
        stage = _tessellate_fixture('testMixedSurfaces.usda')
        meshes = _meshes(stage)
        self.assertTrue(meshes, "testMixedSurfaces: no meshes produced")
        # Positive signed volume: a mis-packed (naive all-NURBS cursor) solid
        # either fails to build the wall faces or inverts, collapsing this.
        for mesh in meshes:
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertGreater(
                vol, 0.0,
                f"testMixedSurfaces: signed volume {vol} <= 0 "
                f"(mixed-family surface packing mis-resolved)")
        # Exact cylinder bbox: the walls (cylinder family) drive x,y = +/-3 and
        # the caps (NURBS family) drive z = 0 and 5. A cursor that read a
        # cylinder's params into a NURBS cap slot (or vice versa) would move
        # these bounds.
        bbox = _mesh_bbox(stage)
        self.assertIsNotNone(bbox, "testMixedSurfaces: empty mesh")
        (xmin, ymin, zmin), (xmax, ymax, zmax) = bbox
        for got, exp, name in ((xmin, -3.0, 'xmin'), (xmax, 3.0, 'xmax'),
                               (ymin, -3.0, 'ymin'), (ymax, 3.0, 'ymax'),
                               (zmin, 0.0, 'zmin'), (zmax, 5.0, 'zmax')):
            self.assertAlmostEqual(
                got, exp, delta=0.05,
                msg=f"testMixedSurfaces: {name} {got:.4f} != {exp:.1f} "
                    f"(mixed-family surface packing mis-resolved)")

    def test_MixedCurvesWithPcurves_Area(self):
        # One NURBS sheet trimmed by a loop mixing line/NURBS/circle 3D edges,
        # each with an authored pcurve. The pcurve (hasTrimCurves) branch builds
        # every wire edge from its 2D pcurve, so the mixed 3D-edge families never
        # reach the NURBS-only edges[] fallback -- the sheet meshes to its exact
        # trimmed region: rectangle [0,4]x[0,3] (area 12) plus the left
        # semicircular bulge (pi*1.5^2/2). Geometry-based, OCCT-meshing
        # independent. A regression that dropped the analytic (line/circle) edges
        # would shrink or open the region and move this area.
        stage = _tessellate_fixture('testMixedCurvesWithPcurves.usda')
        expected = 12.0 + 0.5 * math.pi * 1.5 * 1.5
        area = _total_surface_area(stage)
        self.assertAlmostEqual(
            area, expected, delta=0.2,
            msg=f"mixed-curve sheet area {area:.3f} != {expected:.3f} "
                f"(a mixed 3D-edge family was dropped?)")

    def test_MixedSurfaces_CapsTrimmed(self):
        # A single-loop NURBS cap trimmed only by an analytic circle 3D edge (no
        # authored curveUv) now wire-trims to the r=3 disk. brepBuilder.cpp
        # widened the derive-trim gate from `attemptTrim = analyticSurf ||
        # numLoops > 1` to also cover single-loop NURBS faces that carry boundary
        # edges (any face with a non-empty loop attempts the wire-trim, with the
        # analyzer-reject -> two-pass-retry -> natural-bounds ladder as the safety
        # net). HDOCCT_TRIM_HIST now shows both caps as nurbs -> trimOK. The two
        # analytic cylinder walls also trim (trimOK), so the capped cylinder
        # meshes watertight at signed volume pi*r^2*L = pi*9*5 ~= 141.37 (chord
        # deflection on the walls leaves ~140). Was an expectedFailure at ~33.3
        # (untrimmed 6x6 square caps); flipped to a normal assertion once the
        # derive path learned to wire-trim single-loop NURBS faces. The fixture's
        # two cap faceuse:orientationType entries were also corrected (see the
        # fixture header) -- they had inverted signs that meshed both caps inward.
        stage = _tessellate_fixture('testMixedSurfaces.usda')
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertAlmostEqual(
                vol, math.pi * 9.0 * 5.0, delta=3.0,
                msg=f"trimmed capped-cylinder volume {vol:.2f} != ~141.37")


def _mesh_z_range(stage):
    """(zmin, zmax) over all mesh points, plus max radius in the XY plane."""
    zmin = zmax = None
    rmax = 0.0
    for mesh in _meshes(stage):
        for p in mesh.GetPointsAttr().Get():
            zmin = p[2] if zmin is None else min(zmin, p[2])
            zmax = p[2] if zmax is None else max(zmax, p[2])
            rmax = max(rmax, math.hypot(p[0], p[1]))
    return zmin, zmax, rmax


class TestForcedFallbackCone(unittest.TestCase):
    """Cone axial->slant v-conversion on the parametric face:range fallback.

    testForcedFallbackCone is a full cone (base radius 5 at z=0, apex (0,0,10),
    semiAngle=atan(0.5)) authored with NO curveUv: one lateral face whose only
    boundary edge is an apex-to-rim meridian seam, face:range covering the full
    u-period and the full AXIAL v-height [0,10]. The 3D-edge wire cannot bound
    the apex-enclosing patch, so the builder routes to the !hasTrimCurves
    parametric face:range fallback (verified via HDOCCT_TRIM_HIST -> parmFB on
    the cone row). The schema authors face:range v as AXIAL distance, but OCCT's
    Geom_ConicalSurface v is SLANT (v_slant = v_axial / cos(semiAngle)); fed raw
    the patch is foreshortened by cos(semiAngle) ~= 0.894 -- its base collapses
    from radius 5 / z=0 to radius ~4.47 / z~1.06 and the meshed lateral area
    drops from pi*R*slant ~= 175.6 to ~139.6. The conversion (debt register
    row 1) restores the full patch.
    """

    def test_ForcedFallbackCone_FullHeightAndArea(self):
        stage = _tessellate_fixture('testForcedFallbackCone.usda')
        # Lateral area of the full cone: pi * R * slant, R=5, slant=sqrt(125).
        expected = math.pi * 5.0 * math.sqrt(125.0)   # ~= 175.62
        area = _total_surface_area(stage)
        self.assertGreater(area, 0.0, "empty mesh")
        # Foreshortened (raw axial v) meshes ~139.6; converted meshes ~174.5
        # (chord deflection undershoots the true 175.6). A delta of 4 excludes
        # the ~36-unit foreshortening error while allowing the deflection.
        self.assertAlmostEqual(
            area, expected, delta=4.0,
            msg=f"cone lateral area {area:.2f} != {expected:.2f} "
                f"(axial->slant v conversion regressed? foreshortened ~139.6)")
        # Geometry: the patch must span the full axial height (apex z=10 down to
        # base z=0) and reach the full base radius 5. Foreshortening leaves
        # zmin~1.06 and rmax~4.47.
        zmin, zmax, rmax = _mesh_z_range(stage)
        self.assertAlmostEqual(zmin, 0.0, delta=0.1,
                               msg=f"cone base z {zmin:.3f} != 0 (foreshortened)")
        self.assertAlmostEqual(zmax, 10.0, delta=0.1,
                               msg=f"cone apex z {zmax:.3f} != 10")
        self.assertAlmostEqual(rmax, 5.0, delta=0.1,
                               msg=f"cone base radius {rmax:.3f} != 5 (foreshortened)")


class TestEllipseXrLtYrPartialArc(unittest.TestCase):
    """xr<yr ellipse frame-swap: authored edge:range remapped by -pi/2.

    testEllipseXrLtYrArc is a planar (z=0) three-quarter elliptical sector:
    center -> straight to (0,4) -> 270-degree ellipse arc (xRadius=2, yRadius=4,
    param t=pi/2..2pi through (-2,0),(0,-4)) -> straight to (2,0) -> back to
    center, authored WITHOUT curveUv (derived-trim ellipse path). Because
    xRadius < yRadius, OCCT's major>=minor requirement forces the builder to
    swap the radii and rotate the frame +pi/2, which reparametrizes the ellipse;
    the authored edge:range must then be remapped by -pi/2 so the intended arc
    is selected (debt register row 5). This pins the correct 3/4 sector:
    area = (3/4)*pi*xr*yr = 6*pi ~= 18.85 and bbox x=[-2,2], y=[-4,4]. It is a
    conformance + characterization fixture for the ellipse-swap path; a
    full-period ellipse would be insensitive to the shift, so a partial arc is
    used to exercise arc selection.
    """

    def test_EllipseXrLtYr_ThreeQuarterSector(self):
        stage = _tessellate_fixture('testEllipseXrLtYrArc.usda')
        expected = 0.75 * math.pi * 2.0 * 4.0   # ~= 18.85
        area = _total_surface_area(stage)
        self.assertGreater(area, 0.0, "empty mesh")
        self.assertAlmostEqual(
            area, expected, delta=0.4,
            msg=f"ellipse sector area {area:.3f} != {expected:.3f} "
                f"(wrong arc selected? a quarter sector meshes ~6.28)")
        # bbox: the 270-degree arc reaches -xr,+xr in X and -yr,+yr in Y. A
        # collapsed quarter arc would leave x>=0, y>=0 only.
        bbox = _mesh_bbox(stage)
        self.assertIsNotNone(bbox, "empty mesh")
        (xmin, ymin, _), (xmax, ymax, _) = bbox
        self.assertAlmostEqual(xmin, -2.0, delta=0.1,
                               msg=f"sector xmin {xmin:.3f} != -2 (arc?)")
        self.assertAlmostEqual(xmax, 2.0, delta=0.1,
                               msg=f"sector xmax {xmax:.3f} != 2")
        self.assertAlmostEqual(ymin, -4.0, delta=0.1,
                               msg=f"sector ymin {ymin:.3f} != -4 (arc?)")
        self.assertAlmostEqual(ymax, 4.0, delta=0.1,
                               msg=f"sector ymax {ymax:.3f} != 4")


if __name__ == '__main__':
    unittest.main()
