#!/pxrpythonsubst
#
# Copyright 2024 NVIDIA Corporation
# SPDX-License-Identifier: Apache-2.0

"""Tests for the usdsolidtessellate CLI and tessellation correctness.

Runs the CLI against the 10 fixtures in fixtures/ and checks vertex
counts, winding (signed volume), and mesh properties.

Vertex-count baselines were validated to be identical on two independent
configurations: Linux GCC 13 + OCCT 7.8.1 and Windows MSVC (VS 2026) +
OCCT 8.0.0 (vcpkg). Curved-surface counts are deterministic for a given
OCCT meshing algorithm; if a future OCCT changes them, update the
baselines deliberately.
"""

from pxr import Usd, UsdGeom
import math
import os
import subprocess
import tempfile
import unittest


# Expected total vertex counts per fixture (regression baseline).
#
# The hole/pocket fixtures (testPlaneWithHole, testCubeWithHole,
# testFilletedCubeWithHole, testDepressedPlane) are generated by the OCCT
# exporter (tools/brepExport.cpp) so their trim pcurves are guaranteed
# consistent with each face's surface parameterization. Their counts were
# re-validated on Linux GCC 13 + OCCT 7.8.1 after the curveUv (pcurve)
# trimming path landed; re-check on Windows + OCCT 8.0.0 if that toolchain
# changes the meshing.
EXPECTED_VERT_COUNTS = {
    # testCylinder was regenerated as an EDGED NURBS solid (OCCT exporter,
    # seam+rim edges, proposal rule 424) replacing the earlier edgeless
    # single-periodic-NURBS form; its meshing density changed, so it was
    # re-baselined (Linux GCC 13 + OCCT 7.8.1).
    #
    # testCone was regenerated as the analytic (BrepSurfaceConeAPI) solid to
    # remove the two degenerate apex edges of the earlier edged-NURBS form
    # (proposal rule 381: no degenerate geometry). Two seam-meridian edges + a
    # base rim, the apex is a converging vertex (no zero-length edge); the
    # hdOcct builder closes the apex via the parametric pole-closure fallback.
    # Re-baselined 281 -> 104 (Linux GCC 13 + OCCT 7.8.1); meshes to signed
    # volume +256.8 vs true (1/3)*pi*5^2*10 = 261.8 (chord deflection on the
    # curved lateral surface + apex fan).
    'testCone.usda': 104,
    'testCube.usda': 24,
    'testCubeWithHole.usda': 148,
    'testCylinder.usda': 124,
    'testDepressedPlane.usda': 122,
    # testDepressedPlaneSeamSplit is the SAME depressed plane authored under the
    # proposed producer convention "split full-period periodic faces at the
    # seam": the full-period (u=0..2pi) cylindrical well wall is split at the
    # seam and at u=pi into two half-period wall faces. A reader that
    # mis-tessellates full-period faces (e.g. SMLib on the unsplit twin) can then
    # verify the convention with zero reader changes; hdOcct (full-period
    # capable) meshes the split form to the SAME trimmed areas as the unsplit
    # twin (see test_DepressedPlaneSeamSplit_Pocket) -- proving the split
    # encoding does not regress a full-period consumer. The extra u=pi seam edges
    # + two half-walls raise the vert count (122 -> 136); re-baselined Linux GCC
    # 13 + OCCT 7.8.1.
    'testDepressedPlaneSeamSplit.usda': 136,
    # testFilletedCube was regenerated degenerate-edge-free: the earlier form
    # closed each of the 8 cube-corner spherical blends with a zero-length
    # corner edge (all control vertices equal), which BrepArrayDegenerateEdges
    # (BA.230) flags. The corners are now converging vertices (proposal rule
    # 381 / rule 428); the corner blend patches mesh through the builder's NURBS
    # pcurve path. Re-baselined 512 -> 496 (Linux GCC 13 + OCCT 7.8.1); signed
    # volume +974.9 (box 10^3 minus the 12 edge + 8 corner fillet volumes).
    'testFilletedCube.usda': 496,
    'testFilletedCubeWithHole.usda': 620,
    'testPlane.usda': 4,
    'testPlaneWithHole.usda': 33,
    # testSphere was regenerated as the analytic (BrepSurfaceSphereAPI) solid to
    # remove the degenerate pole edges of the earlier edged-NURBS form (proposal
    # rule 381: no degenerate geometry). Two seam-meridian edges, poles are
    # converging vertices, no zero-length edges; re-baselined (Linux GCC 13 +
    # OCCT 7.8.1). Meshes slightly under the true 4/3*pi*5^3 = 523.6 (chord
    # deflection on the curved surface).
    'testSphere.usda': 306,
    'testTwoBoxes.usda': 48,
    'testProducerCube.usda': 24,
}

PRIM_PATHS = {
    'testCone.usda': '/World/Cone',
    'testCube.usda': '/World/Cube',
    'testCubeWithHole.usda': '/World/CubeWithHole',
    'testCylinder.usda': '/World/Cylinder',
    'testDepressedPlane.usda': '/World/DepressedPlane',
    'testDepressedPlaneSeamSplit.usda': '/World/DepressedPlane',
    'testFilletedCube.usda': '/World/FilletedCube',
    'testFilletedCubeWithHole.usda': '/World/FilletedCubeWithHole',
    'testPlane.usda': '/World/Plane',
    'testPlaneWithHole.usda': '/World/PlaneWithHole',
    'testSphere.usda': '/World/Sphere',
    'testTwoBoxes.usda': '/World/TwoBoxes',
    'testAnalyticPlane.usda': '/World/AnPlane',
    'testAnalyticCylinder.usda': '/World/AnalyticCyl',
    'testAnalyticCone.usda': '/World/AnCone',
    'testAnalyticSphere.usda': '/World/AnSphere',
    'testAnalyticTorus.usda': '/World/AnTorus',
    'testAnalyticCylinderEdges.usda': '/World/CylEdge',
    'testAnalyticConeEdges.usda': '/World/ConeEdge',
    'testFullSphere.usda': '/World/FullSphere',
    'testProducerCube.usda': '/World/Cube',
    'testVoidOnlySphere.usda': '/World/VoidSphere',
}

# Closed solids: signed volume must be positive (outward winding).
CLOSED_SOLIDS = [
    'testCone.usda',
    'testCube.usda',
    'testCubeWithHole.usda',
    'testCylinder.usda',
    'testFilletedCube.usda',
    'testFilletedCubeWithHole.usda',
    'testSphere.usda',
    'testTwoBoxes.usda',
    'testProducerCube.usda',
]

# Analytic-surface fixtures -> (expected meshed area, absolute tolerance).
#
# These exercise the analytic surface readers: each face is built from its
# schema parameters (origin/axis/refDirection + radius/semiAngle/...) rather
# than NURBS control points. The five surface types use the authored curveUv
# (pcurve) trimming path; the *Edges fixtures additionally exercise the
# analytic 3D-edge path (analytic surface trimmed by analytic circle/line
# curves with no authored curveUv). Areas are geometric and independent of
# the OCCT meshing algorithm; curved surfaces mesh slightly under their true
# area (chord-height deflection), so the tolerance permits a small undershoot.
ANALYTIC_AREA_FIXTURES = {
    'testAnalyticPlane.usda':         (12.0, 0.5),
    'testAnalyticCylinder.usda':      (2.0 * math.pi * 3.0 * 5.0, 2.0),
    'testAnalyticCone.usda':          (25.28, 1.0),
    'testAnalyticSphere.usda':        (59.98, 2.0),
    'testAnalyticTorus.usda':         (203.22, 6.0),
    'testAnalyticCylinderEdges.usda': (70.686, 2.5),
    'testAnalyticConeEdges.usda':     (25.28, 1.5),
    # Full sphere (r=2) encoded as a producer does it: one face whose only edge is
    # a pole-to-pole meridian SEAM, no curveUv, face:range = the full sphere. The
    # 3D-edge wire cannot bound a pole-enclosing patch, so this exercises the
    # parametric face:range fallback (OCCT adds the seam + degenerate pole edges).
    'testFullSphere.usda':            (4.0 * math.pi * 4.0, 2.0),
}


def _get_fixtures_dir():
    """Fixtures live next to the installed test (ctest) or the script."""
    for base in (os.getcwd(),
                 os.path.dirname(os.path.abspath(__file__))):
        d = os.path.join(base, 'fixtures')
        if os.path.isdir(d):
            return d
        d = os.path.join(base, 'testUsdSolidTessellation', 'fixtures')
        if os.path.isdir(d):
            return d
    raise RuntimeError("fixtures directory not found")


def _get_tessellator_bin():
    """Find the usdsolidtessellate binary."""
    env_bin = os.environ.get('USDSOLIDTESSELLATE_BIN')
    if env_bin and os.path.isfile(env_bin):
        return env_bin
    from shutil import which
    path_bin = which('usdsolidtessellate')
    if path_bin:
        return path_bin
    return 'usdsolidtessellate'


def _run_tessellator(input_path, output_path, prim_path):
    result = subprocess.run(
        [_get_tessellator_bin(), input_path, output_path, prim_path],
        capture_output=True, text=True, timeout=120)
    return result.returncode, result.stdout, result.stderr


def _tessellate_fixture(fixture_name):
    input_path = os.path.join(_get_fixtures_dir(), fixture_name)
    prim_path = PRIM_PATHS[fixture_name]
    fd, output_path = tempfile.mkstemp(suffix='.usda')
    os.close(fd)
    rc, stdout, stderr = _run_tessellator(input_path, output_path, prim_path)
    if rc != 0:
        os.unlink(output_path)
        raise RuntimeError(
            f"Tessellation failed for {fixture_name}: {stdout} {stderr}")
    stage = Usd.Stage.Open(output_path)
    os.unlink(output_path)
    return stage


def _meshes(stage):
    return [UsdGeom.Mesh(p) for p in stage.TraverseAll()
            if p.GetTypeName() == 'Mesh']


def _signed_volume(points, face_vertex_counts, face_vertex_indices):
    """Signed volume of a triangle mesh (positive = outward winding)."""
    volume = 0.0
    idx = 0
    for count in face_vertex_counts:
        if count != 3:
            idx += count
            continue
        v0 = points[face_vertex_indices[idx]]
        v1 = points[face_vertex_indices[idx + 1]]
        v2 = points[face_vertex_indices[idx + 2]]
        volume += (v0[0] * (v1[1] * v2[2] - v1[2] * v2[1]) +
                   v0[1] * (v1[2] * v2[0] - v1[0] * v2[2]) +
                   v0[2] * (v1[0] * v2[1] - v1[1] * v2[0]))
        idx += count
    return volume / 6.0


class TestTessellationVertexCounts(unittest.TestCase):
    """Each fixture produces the validated vertex count (regression)."""

    def _check_fixture(self, fixture_name):
        stage = _tessellate_fixture(fixture_name)
        total_verts = sum(len(m.GetPointsAttr().Get())
                          for m in _meshes(stage))
        expected = EXPECTED_VERT_COUNTS[fixture_name]
        self.assertEqual(total_verts, expected,
                         f"{fixture_name}: expected {expected} verts, "
                         f"got {total_verts}")

    def test_Cube(self):
        self._check_fixture('testCube.usda')

    def test_Sphere(self):
        self._check_fixture('testSphere.usda')

    def test_Cylinder(self):
        self._check_fixture('testCylinder.usda')

    def test_Cone(self):
        self._check_fixture('testCone.usda')

    def test_CubeWithHole(self):
        self._check_fixture('testCubeWithHole.usda')

    def test_DepressedPlane(self):
        self._check_fixture('testDepressedPlane.usda')

    def test_DepressedPlaneSeamSplit(self):
        self._check_fixture('testDepressedPlaneSeamSplit.usda')

    def test_FilletedCube(self):
        self._check_fixture('testFilletedCube.usda')

    def test_FilletedCubeWithHole(self):
        self._check_fixture('testFilletedCubeWithHole.usda')

    def test_Plane(self):
        self._check_fixture('testPlane.usda')

    def test_PlaneWithHole(self):
        self._check_fixture('testPlaneWithHole.usda')

    def test_TwoBoxes(self):
        self._check_fixture('testTwoBoxes.usda')

    def test_ProducerCube(self):
        self._check_fixture('testProducerCube.usda')


class TestTessellationWindingOrder(unittest.TestCase):
    """Signed volume is positive for closed solids.

    Winding and normals are driven by the authored faceuse:orientationType.
    For the hand-authored fixtures (single solidRegion shell, interleaved
    faceuses) the first faceuse of each face's pair is the outward side; for
    producer fixtures (voidRegion + solidRegion shells, faceuses grouped by
    shell with faceuse:faceIndex) the voidRegion faceuse is the outward side.
    Either way outward orientation is exact, not heuristic.
    """

    def _check_winding(self, fixture_name):
        stage = _tessellate_fixture(fixture_name)
        meshes = _meshes(stage)
        self.assertTrue(meshes, f"{fixture_name}: no meshes produced")
        for mesh in meshes:
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertGreater(vol, 0,
                               f"{fixture_name}: signed volume {vol} <= 0 "
                               f"(bad winding)")

    def test_Cube(self):
        self._check_winding('testCube.usda')

    def test_Sphere(self):
        self._check_winding('testSphere.usda')

    def test_Cylinder(self):
        self._check_winding('testCylinder.usda')

    def test_Cone(self):
        self._check_winding('testCone.usda')

    def test_CubeWithHole(self):
        self._check_winding('testCubeWithHole.usda')

    def test_TwoBoxes(self):
        self._check_winding('testTwoBoxes.usda')

    def test_ProducerCube(self):
        # Producer radial-edge layout (voidRegion + solidRegion, faceuses
        # grouped by shell): the 10x10x10 box must keep outward winding AND its
        # full volume. The legacy 2*fi orientation lookup straddles the two
        # shells here and mis-orients half the faces, collapsing the signed
        # volume toward zero -- so assert the magnitude, not just the sign.
        stage = _tessellate_fixture('testProducerCube.usda')
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertAlmostEqual(
                vol, 1000.0, delta=1.0,
                msg=f"testProducerCube: signed volume {vol} != 1000 "
                    f"(orientation/closure error)")

    def test_VoidOnlySphere(self):
        # Void-only body (voidRegion, no solidRegion) whose interleaved coedge
        # pair is ordered ("opposite","same"). The fixed faceuse[2*fi] lookup
        # reads "opposite" and flips the whole sphere inward; the content-based
        # pick (layout C) keeps it outward. Expect a positive, sphere-sized
        # signed volume (4/3*pi*2^3 ~= 33.5, meshed slightly under).
        stage = _tessellate_fixture('testVoidOnlySphere.usda')
        for mesh in _meshes(stage):
            vol = _signed_volume(mesh.GetPointsAttr().Get(),
                                 mesh.GetFaceVertexCountsAttr().Get(),
                                 mesh.GetFaceVertexIndicesAttr().Get())
            self.assertGreater(
                vol, 20.0,
                msg=f"testVoidOnlySphere: signed volume {vol} -- expected "
                    f"~33.5 outward; <=0 means the layout-C void-only "
                    f"orientation regressed (flipped inward)")


class TestTessellationMeshProperties(unittest.TestCase):
    """Output meshes have correct properties."""

    def test_NormalsPresent(self):
        stage = _tessellate_fixture('testSphere.usda')
        for mesh in _meshes(stage):
            normals = mesh.GetNormalsAttr().Get()
            points = mesh.GetPointsAttr().Get()
            self.assertIsNotNone(normals)
            self.assertEqual(len(normals), len(points))

    def test_NormalsUnitLength(self):
        stage = _tessellate_fixture('testCube.usda')
        for mesh in _meshes(stage):
            for n in mesh.GetNormalsAttr().Get():
                length = math.sqrt(n[0]**2 + n[1]**2 + n[2]**2)
                self.assertAlmostEqual(length, 1.0, places=4)

    def test_SubdivisionSchemeNone(self):
        stage = _tessellate_fixture('testCube.usda')
        for mesh in _meshes(stage):
            self.assertEqual(mesh.GetSubdivisionSchemeAttr().Get(), 'none')

    def test_FaceCountsNonZero(self):
        for fixture_name in EXPECTED_VERT_COUNTS:
            stage = _tessellate_fixture(fixture_name)
            total_faces = sum(len(m.GetFaceVertexCountsAttr().Get())
                              for m in _meshes(stage))
            self.assertGreater(total_faces, 0,
                               f"{fixture_name}: no faces produced")


def _planar_area_at_z(stage, z, tol=1e-4):
    """Sum of triangle areas whose three vertices all lie on plane Z=z."""
    area = 0.0
    for mesh in _meshes(stage):
        points = mesh.GetPointsAttr().Get()
        fvc = mesh.GetFaceVertexCountsAttr().Get()
        fvi = mesh.GetFaceVertexIndicesAttr().Get()
        idx = 0
        for count in fvc:
            tri = [points[fvi[idx + k]] for k in range(count)]
            idx += count
            if count != 3 or not all(abs(p[2] - z) < tol for p in tri):
                continue
            ux, uy, uz = (tri[1][0] - tri[0][0], tri[1][1] - tri[0][1],
                          tri[1][2] - tri[0][2])
            vx, vy, vz = (tri[2][0] - tri[0][0], tri[2][1] - tri[0][1],
                          tri[2][2] - tri[0][2])
            cx, cy, cz = (uy * vz - uz * vy, uz * vx - ux * vz,
                          ux * vy - uy * vx)
            area += 0.5 * math.sqrt(cx * cx + cy * cy + cz * cz)
    return area


def _total_surface_area(stage):
    area = 0.0
    for mesh in _meshes(stage):
        points = mesh.GetPointsAttr().Get()
        fvc = mesh.GetFaceVertexCountsAttr().Get()
        fvi = mesh.GetFaceVertexIndicesAttr().Get()
        idx = 0
        for count in fvc:
            if count == 3:
                a, b, c = (points[fvi[idx + k]] for k in range(3))
                ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
                vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
                cx, cy, cz = (uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx)
                area += 0.5 * math.sqrt(cx*cx + cy*cy + cz*cz)
            idx += count
    return area


class TestTrimmedFaceArea(unittest.TestCase):
    """Multi-loop (hole/pocket) faces mesh their full trimmed area.

    Regression for the curveUv (pcurve) trimming path. Before it landed,
    faces trimmed via projected 3D-edge wires meshed to a small fraction
    of their true area (testCubeWithHole's punctured face: ~12.5 of ~71.7).
    Now each loop edge is built directly from its authored 2D pcurve, so
    the trimmed area is exact. Geometry-based (OCCT-meshing-independent).
    """

    def test_PlaneWithHole_FullArea(self):
        # 20x20 sheet minus a r=3 hole.
        stage = _tessellate_fixture('testPlaneWithHole.usda')
        expected = 400.0 - math.pi * 9.0
        area = _total_surface_area(stage)
        self.assertAlmostEqual(area, expected, delta=2.0,
                               msg=f"sheet area {area:.2f} != {expected:.2f}")

    def test_CubeWithHole_PuncturedFaces(self):
        # Top (z=10) and bottom (z=0) faces are each 10x10 minus a r=3 hole.
        stage = _tessellate_fixture('testCubeWithHole.usda')
        expected = 100.0 - math.pi * 9.0
        for z in (0.0, 10.0):
            area = _planar_area_at_z(stage, z)
            self.assertAlmostEqual(
                area, expected, delta=1.0,
                msg=f"z={z} punctured face area {area:.2f} != {expected:.2f}")

    def test_DepressedPlane_Pocket(self):
        # 20x20 sheet with a r=3 cylindrical pocket of depth 5: the top must
        # be a real opening (zero meshed area inside the hole circle), and a
        # bottom cap must exist at z=-5.
        stage = _tessellate_fixture('testDepressedPlane.usda')
        top = _planar_area_at_z(stage, 0.0)
        bottom = _planar_area_at_z(stage, -5.0)
        self.assertAlmostEqual(top, 400.0 - math.pi * 9.0, delta=2.0,
                               msg=f"pocket top area {top:.2f}")
        self.assertAlmostEqual(bottom, math.pi * 9.0, delta=2.0,
                               msg=f"pocket bottom cap area {bottom:.2f}")

    def test_DepressedPlaneSeamSplit_Pocket(self):
        # Seam-split twin: the SAME depressed plane with the full-period well
        # wall split at the seam (u=0/2pi) and at u=pi into two half-period wall
        # faces. This asserts the split encoding meshes to the SAME trimmed areas
        # as the unsplit twin (test_DepressedPlane_Pocket) -- a permanent
        # split==unsplit equivalence gate on a full-period-capable consumer,
        # complementing the SMLib cross-kernel proof that the split form lets a
        # full-period-limited reader get exact numbers with no reader changes.
        stage = _tessellate_fixture('testDepressedPlaneSeamSplit.usda')
        top = _planar_area_at_z(stage, 0.0)
        bottom = _planar_area_at_z(stage, -5.0)
        self.assertAlmostEqual(top, 400.0 - math.pi * 9.0, delta=2.0,
                               msg=f"seam-split pocket top area {top:.2f}")
        self.assertAlmostEqual(bottom, math.pi * 9.0, delta=2.0,
                               msg=f"seam-split pocket bottom cap area {bottom:.2f}")


class TestTessellationErrorHandling(unittest.TestCase):
    """Bad inputs return errors without crashing."""

    def test_NonexistentPrimPath(self):
        input_path = os.path.join(_get_fixtures_dir(), 'testCube.usda')
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, _, _ = _run_tessellator(input_path, output_path,
                                    '/World/DoesNotExist')
        if os.path.exists(output_path):
            os.unlink(output_path)
        self.assertNotEqual(rc, 0)

    def test_NonexistentInputFile(self):
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, _, _ = _run_tessellator('does_not_exist_xyz.usda',
                                    output_path, '/World/Cube')
        if os.path.exists(output_path):
            os.unlink(output_path)
        self.assertNotEqual(rc, 0)


# Pcurve-less ("derived-trim") twins: fixtures/derivedTrims/<name>NoPcurves.usda
# are generated from the originals by removing the five brep:curveUv:nurb:*
# arrays and dropping the BrepCurveUvNurbAPI schema, so face trims are DERIVED
# from the 3D edge curves at read time. brep:curveUv is optional per proposal
# #109 (the 3D edge curve is the model truth), so a conformant consumer must
# handle both encodings. These counts are the derived-trim tessellation (coarser
# than the authored-pcurve original for curved faces, identical for planar).
# See fixtures/derivedTrims/README.md.
PCURVELESS_TWIN_VERTS = {
    'testCubeNoPcurves.usda': 24,
    'testCylinderNoPcurves.usda': 72,
    'testConeNoPcurves.usda': 106,
    'testFilletedCubeNoPcurves.usda': 512,
    'testCubeWithHoleNoPcurves.usda': 148,
    'testPlaneWithHoleNoPcurves.usda': 33,
    'testDepressedPlaneNoPcurves.usda': 97,
}


class TestPcurveLessTwins(unittest.TestCase):
    """Derived-trim twins tessellate correctly with no authored pcurves."""

    def _tessellate_twin(self, twin_name):
        input_path = os.path.join(_get_fixtures_dir(), 'derivedTrims', twin_name)
        stage_in = Usd.Stage.Open(input_path)
        prim = next(p for p in stage_in.Traverse()
                    if p.GetTypeName() == 'BrepArray')
        fd, output_path = tempfile.mkstemp(suffix='.usda')
        os.close(fd)
        rc, so, se = _run_tessellator(input_path, output_path,
                                      prim.GetPath().pathString)
        if rc != 0:
            os.unlink(output_path)
            raise RuntimeError(f"{twin_name}: tessellation failed: {so} {se}")
        stage = Usd.Stage.Open(output_path)
        os.unlink(output_path)
        return stage

    def test_twins_tessellate(self):
        for twin, expected in PCURVELESS_TWIN_VERTS.items():
            with self.subTest(twin=twin):
                stage = self._tessellate_twin(twin)
                verts = sum(len(m.GetPointsAttr().Get())
                            for m in _meshes(stage))
                self.assertEqual(verts, expected,
                                 f"{twin}: expected {expected} verts, "
                                 f"got {verts}")

    @unittest.expectedFailure
    def test_twin_Sphere_rendersFull(self):
        # testSphere is authored as two seam-split half-lune faces; without
        # pcurves the meridian-only boundary wire cannot close a lune (the
        # degenerate pole/seam edges are absent per rule 381), so the twin
        # renders half a sphere. Expected failure: it flips to XPASS if the
        # pole/seam derive path is ever completed, prompting a baseline update.
        # A sphere authored as a single natural-bound face (testAnalyticSphere)
        # renders correctly pcurve-less. See fixtures/derivedTrims/README.md.
        stage = self._tessellate_twin('testSphereNoPcurves.usda')
        ys = [p[1] for m in _meshes(stage) for p in m.GetPointsAttr().Get()]
        span_y = (max(ys) - min(ys)) if ys else 0.0
        self.assertGreater(span_y, 9.0,
                           "sphere twin should span the full diameter")


class TestAnalyticSurfaceArea(unittest.TestCase):
    """Analytic surfaces tessellate to their exact geometric area.

    Each analytic surface type (plane, cylinder, cone, sphere, torus) is
    constructed from its schema parameters rather than from NURBS control
    points, and trimmed via the authored curveUv (pcurve) path. The *Edges
    fixtures additionally exercise the analytic 3D-edge path: an analytic
    surface trimmed by analytic circle/line curves with no authored curveUv,
    where each edge's pcurve is projected onto the surface. Areas are
    geometry-based and independent of the OCCT meshing algorithm.
    """

    def _check_area(self, fixture_name):
        expected, tol = ANALYTIC_AREA_FIXTURES[fixture_name]
        stage = _tessellate_fixture(fixture_name)
        area = _total_surface_area(stage)
        self.assertGreater(area, 0.0, f"{fixture_name}: empty mesh")
        self.assertAlmostEqual(
            area, expected, delta=tol,
            msg=f"{fixture_name}: area {area:.3f} != {expected:.3f}")

    def test_AnalyticPlane(self):
        self._check_area('testAnalyticPlane.usda')

    def test_AnalyticCylinder(self):
        self._check_area('testAnalyticCylinder.usda')

    def test_AnalyticCone(self):
        self._check_area('testAnalyticCone.usda')

    def test_AnalyticSphere(self):
        self._check_area('testAnalyticSphere.usda')

    def test_AnalyticTorus(self):
        self._check_area('testAnalyticTorus.usda')

    def test_AnalyticCylinderEdges(self):
        self._check_area('testAnalyticCylinderEdges.usda')

    def test_AnalyticConeEdges(self):
        self._check_area('testAnalyticConeEdges.usda')

    def test_FullSphere(self):
        # Pole-enclosing analytic face (full sphere via meridian seam, no
        # curveUv) -> parametric face:range fallback. Common in real CAD output.
        self._check_area('testFullSphere.usda')


if __name__ == '__main__':
    unittest.main()
