//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(UsdSolidBrepArray);
TF_WRAP(UsdSolidBrepPointAPI);
TF_WRAP(UsdSolidBrepCurve3dNurbAPI);
TF_WRAP(UsdSolidBrepCurve3dLineAPI);
TF_WRAP(UsdSolidBrepCurve3dCircleAPI);
TF_WRAP(UsdSolidBrepCurve3dEllipseAPI);
TF_WRAP(UsdSolidBrepCurveUvNurbAPI);
TF_WRAP(UsdSolidBrepSurfaceNurbAPI);
TF_WRAP(UsdSolidBrepSurfaceSphereAPI);
TF_WRAP(UsdSolidBrepSurfacePlaneAPI);
TF_WRAP(UsdSolidBrepSurfaceCylinderAPI);
TF_WRAP(UsdSolidBrepSurfaceConeAPI);
TF_WRAP(UsdSolidBrepSurfaceTorusAPI);
TF_WRAP(UsdSolidTokens);
