//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include ".//tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdSolidTokensType::UsdSolidTokensType() :
    bottomEntry("bottomEntry", TfToken::Immortal),
    brep("brep", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dCircleAxis("brep:__INSTANCE_NAME__:curve3d:circle:axis", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dCircleCenter("brep:__INSTANCE_NAME__:curve3d:circle:center", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dCircleRadius("brep:__INSTANCE_NAME__:curve3d:circle:radius", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dCircleRefDirection("brep:__INSTANCE_NAME__:curve3d:circle:refDirection", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dEllipseAxis("brep:__INSTANCE_NAME__:curve3d:ellipse:axis", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dEllipseCenter("brep:__INSTANCE_NAME__:curve3d:ellipse:center", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dEllipseRefDirection("brep:__INSTANCE_NAME__:curve3d:ellipse:refDirection", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dEllipseXRadius("brep:__INSTANCE_NAME__:curve3d:ellipse:xRadius", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dEllipseYRadius("brep:__INSTANCE_NAME__:curve3d:ellipse:yRadius", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dLineDirection("brep:__INSTANCE_NAME__:curve3d:line:direction", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dLineOrigin("brep:__INSTANCE_NAME__:curve3d:line:origin", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dNurbControlVertices("brep:__INSTANCE_NAME__:curve3d:nurb:controlVertices", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dNurbKnots("brep:__INSTANCE_NAME__:curve3d:nurb:knots", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dNurbOrder("brep:__INSTANCE_NAME__:curve3d:nurb:order", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dNurbVertexCount("brep:__INSTANCE_NAME__:curve3d:nurb:vertexCount", TfToken::Immortal),
    brep_MultipleApplyTemplate_Curve3dNurbWeights("brep:__INSTANCE_NAME__:curve3d:nurb:weights", TfToken::Immortal),
    brep_MultipleApplyTemplate_PointPosition("brep:__INSTANCE_NAME__:point:position", TfToken::Immortal),
    brepCurveUvNurbControlVertices("brep:curveUv:nurb:controlVertices", TfToken::Immortal),
    brepCurveUvNurbKnots("brep:curveUv:nurb:knots", TfToken::Immortal),
    brepCurveUvNurbOrder("brep:curveUv:nurb:order", TfToken::Immortal),
    brepCurveUvNurbVertexCount("brep:curveUv:nurb:vertexCount", TfToken::Immortal),
    brepCurveUvNurbWeights("brep:curveUv:nurb:weights", TfToken::Immortal),
    brepExtent("brep:extent", TfToken::Immortal),
    brepIntersectTol3d("brep:intersectTol3d", TfToken::Immortal),
    brepRegionCount("brep:regionCount", TfToken::Immortal),
    brepSurfaceConeAxis("brep:surface:cone:axis", TfToken::Immortal),
    brepSurfaceConeOrigin("brep:surface:cone:origin", TfToken::Immortal),
    brepSurfaceConeRadius("brep:surface:cone:radius", TfToken::Immortal),
    brepSurfaceConeRefDirection("brep:surface:cone:refDirection", TfToken::Immortal),
    brepSurfaceConeSemiAngle("brep:surface:cone:semiAngle", TfToken::Immortal),
    brepSurfaceCylinderAxis("brep:surface:cylinder:axis", TfToken::Immortal),
    brepSurfaceCylinderOrigin("brep:surface:cylinder:origin", TfToken::Immortal),
    brepSurfaceCylinderRadius("brep:surface:cylinder:radius", TfToken::Immortal),
    brepSurfaceCylinderRefDirection("brep:surface:cylinder:refDirection", TfToken::Immortal),
    brepSurfaceNurbControlVertices("brep:surface:nurb:controlVertices", TfToken::Immortal),
    brepSurfaceNurbUKnots("brep:surface:nurb:uKnots", TfToken::Immortal),
    brepSurfaceNurbUOrder("brep:surface:nurb:uOrder", TfToken::Immortal),
    brepSurfaceNurbUVertexCount("brep:surface:nurb:uVertexCount", TfToken::Immortal),
    brepSurfaceNurbVKnots("brep:surface:nurb:vKnots", TfToken::Immortal),
    brepSurfaceNurbVOrder("brep:surface:nurb:vOrder", TfToken::Immortal),
    brepSurfaceNurbVVertexCount("brep:surface:nurb:vVertexCount", TfToken::Immortal),
    brepSurfaceNurbWeights("brep:surface:nurb:weights", TfToken::Immortal),
    brepSurfacePlaneAxis("brep:surface:plane:axis", TfToken::Immortal),
    brepSurfacePlaneOrigin("brep:surface:plane:origin", TfToken::Immortal),
    brepSurfacePlaneRefDirection("brep:surface:plane:refDirection", TfToken::Immortal),
    brepSurfaceSphereAxis("brep:surface:sphere:axis", TfToken::Immortal),
    brepSurfaceSphereCenter("brep:surface:sphere:center", TfToken::Immortal),
    brepSurfaceSphereRadius("brep:surface:sphere:radius", TfToken::Immortal),
    brepSurfaceSphereRefDirection("brep:surface:sphere:refDirection", TfToken::Immortal),
    brepSurfaceTorusAxis("brep:surface:torus:axis", TfToken::Immortal),
    brepSurfaceTorusMajorRadius("brep:surface:torus:majorRadius", TfToken::Immortal),
    brepSurfaceTorusMinorRadius("brep:surface:torus:minorRadius", TfToken::Immortal),
    brepSurfaceTorusOrigin("brep:surface:torus:origin", TfToken::Immortal),
    brepSurfaceTorusRefDirection("brep:surface:torus:refDirection", TfToken::Immortal),
    edgeCurveType("edge:curveType", TfToken::Immortal),
    edgeRange("edge:range", TfToken::Immortal),
    edgeuseEdgeIndex("edgeuse:edgeIndex", TfToken::Immortal),
    edgeuseNextRadialEUIndex("edgeuse:nextRadialEUIndex", TfToken::Immortal),
    edgeuseOrientationType("edgeuse:orientationType", TfToken::Immortal),
    edgeuseThisRadialEntryType("edgeuse:thisRadialEntryType", TfToken::Immortal),
    edgeVertexIndices("edge:vertexIndices", TfToken::Immortal),
    faceLoopCount("face:loopCount", TfToken::Immortal),
    faceRange("face:range", TfToken::Immortal),
    faceSurfaceType("face:surfaceType", TfToken::Immortal),
    faceTrimType("face:trimType", TfToken::Immortal),
    faceuseFaceIndex("faceuse:faceIndex", TfToken::Immortal),
    faceuseOrientationType("faceuse:orientationType", TfToken::Immortal),
    general("general", TfToken::Immortal),
    loopEdgeuseCount("loop:edgeuseCount", TfToken::Immortal),
    loopVertexIndex("loop:vertexIndex", TfToken::Immortal),
    none("none", TfToken::Immortal),
    opposite("opposite", TfToken::Immortal),
    rectangular("rectangular", TfToken::Immortal),
    regionShellCount("region:shellCount", TfToken::Immortal),
    regionType("region:type", TfToken::Immortal),
    same("same", TfToken::Immortal),
    shellFaceuseCount("shell:faceuseCount", TfToken::Immortal),
    shellPointType("shell:pointType", TfToken::Immortal),
    shellWireEdgeCount("shell:wireEdgeCount", TfToken::Immortal),
    solidRegion("solidRegion", TfToken::Immortal),
    topEntry("topEntry", TfToken::Immortal),
    vertexPointType("vertex:pointType", TfToken::Immortal),
    voidRegion("voidRegion", TfToken::Immortal),
    wireEdgeCurveType("wireEdge:curveType", TfToken::Immortal),
    wireEdgeRange("wireEdge:range", TfToken::Immortal),
    wireEdgeVertexIndices("wireEdge:vertexIndices", TfToken::Immortal),
    BrepArray("BrepArray", TfToken::Immortal),
    BrepCurve3dCircleAPI("BrepCurve3dCircleAPI", TfToken::Immortal),
    BrepCurve3dEllipseAPI("BrepCurve3dEllipseAPI", TfToken::Immortal),
    BrepCurve3dLineAPI("BrepCurve3dLineAPI", TfToken::Immortal),
    BrepCurve3dNurbAPI("BrepCurve3dNurbAPI", TfToken::Immortal),
    BrepCurveUvNurbAPI("BrepCurveUvNurbAPI", TfToken::Immortal),
    BrepPointAPI("BrepPointAPI", TfToken::Immortal),
    BrepSurfaceConeAPI("BrepSurfaceConeAPI", TfToken::Immortal),
    BrepSurfaceCylinderAPI("BrepSurfaceCylinderAPI", TfToken::Immortal),
    BrepSurfaceNurbAPI("BrepSurfaceNurbAPI", TfToken::Immortal),
    BrepSurfacePlaneAPI("BrepSurfacePlaneAPI", TfToken::Immortal),
    BrepSurfaceSphereAPI("BrepSurfaceSphereAPI", TfToken::Immortal),
    BrepSurfaceTorusAPI("BrepSurfaceTorusAPI", TfToken::Immortal),
    allTokens({
        bottomEntry,
        brep,
        brep_MultipleApplyTemplate_Curve3dCircleAxis,
        brep_MultipleApplyTemplate_Curve3dCircleCenter,
        brep_MultipleApplyTemplate_Curve3dCircleRadius,
        brep_MultipleApplyTemplate_Curve3dCircleRefDirection,
        brep_MultipleApplyTemplate_Curve3dEllipseAxis,
        brep_MultipleApplyTemplate_Curve3dEllipseCenter,
        brep_MultipleApplyTemplate_Curve3dEllipseRefDirection,
        brep_MultipleApplyTemplate_Curve3dEllipseXRadius,
        brep_MultipleApplyTemplate_Curve3dEllipseYRadius,
        brep_MultipleApplyTemplate_Curve3dLineDirection,
        brep_MultipleApplyTemplate_Curve3dLineOrigin,
        brep_MultipleApplyTemplate_Curve3dNurbControlVertices,
        brep_MultipleApplyTemplate_Curve3dNurbKnots,
        brep_MultipleApplyTemplate_Curve3dNurbOrder,
        brep_MultipleApplyTemplate_Curve3dNurbVertexCount,
        brep_MultipleApplyTemplate_Curve3dNurbWeights,
        brep_MultipleApplyTemplate_PointPosition,
        brepCurveUvNurbControlVertices,
        brepCurveUvNurbKnots,
        brepCurveUvNurbOrder,
        brepCurveUvNurbVertexCount,
        brepCurveUvNurbWeights,
        brepExtent,
        brepIntersectTol3d,
        brepRegionCount,
        brepSurfaceConeAxis,
        brepSurfaceConeOrigin,
        brepSurfaceConeRadius,
        brepSurfaceConeRefDirection,
        brepSurfaceConeSemiAngle,
        brepSurfaceCylinderAxis,
        brepSurfaceCylinderOrigin,
        brepSurfaceCylinderRadius,
        brepSurfaceCylinderRefDirection,
        brepSurfaceNurbControlVertices,
        brepSurfaceNurbUKnots,
        brepSurfaceNurbUOrder,
        brepSurfaceNurbUVertexCount,
        brepSurfaceNurbVKnots,
        brepSurfaceNurbVOrder,
        brepSurfaceNurbVVertexCount,
        brepSurfaceNurbWeights,
        brepSurfacePlaneAxis,
        brepSurfacePlaneOrigin,
        brepSurfacePlaneRefDirection,
        brepSurfaceSphereAxis,
        brepSurfaceSphereCenter,
        brepSurfaceSphereRadius,
        brepSurfaceSphereRefDirection,
        brepSurfaceTorusAxis,
        brepSurfaceTorusMajorRadius,
        brepSurfaceTorusMinorRadius,
        brepSurfaceTorusOrigin,
        brepSurfaceTorusRefDirection,
        edgeCurveType,
        edgeRange,
        edgeuseEdgeIndex,
        edgeuseNextRadialEUIndex,
        edgeuseOrientationType,
        edgeuseThisRadialEntryType,
        edgeVertexIndices,
        faceLoopCount,
        faceRange,
        faceSurfaceType,
        faceTrimType,
        faceuseFaceIndex,
        faceuseOrientationType,
        general,
        loopEdgeuseCount,
        loopVertexIndex,
        none,
        opposite,
        rectangular,
        regionShellCount,
        regionType,
        same,
        shellFaceuseCount,
        shellPointType,
        shellWireEdgeCount,
        solidRegion,
        topEntry,
        vertexPointType,
        voidRegion,
        wireEdgeCurveType,
        wireEdgeRange,
        wireEdgeVertexIndices,
        BrepArray,
        BrepCurve3dCircleAPI,
        BrepCurve3dEllipseAPI,
        BrepCurve3dLineAPI,
        BrepCurve3dNurbAPI,
        BrepCurveUvNurbAPI,
        BrepPointAPI,
        BrepSurfaceConeAPI,
        BrepSurfaceCylinderAPI,
        BrepSurfaceNurbAPI,
        BrepSurfacePlaneAPI,
        BrepSurfaceSphereAPI,
        BrepSurfaceTorusAPI
    })
{
}

TfStaticData<UsdSolidTokensType> UsdSolidTokens;

PXR_NAMESPACE_CLOSE_SCOPE
