// Copyright 2024 NVIDIA Corporation
// SPDX-License-Identifier: Apache-2.0
//
// USD Solid Tessellator - API Export Macros

#ifndef USD_SOLID_TESSELLATOR_API_H
#define USD_SOLID_TESSELLATOR_API_H

#include "pxr/base/arch/export.h"

#if defined(USDSOLIDTESSELLATOR_EXPORTS)
#   define USDSOLIDTESSELLATOR_API ARCH_EXPORT
#   define USDSOLIDTESSELLATOR_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#   define USDSOLIDTESSELLATOR_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#else
#   define USDSOLIDTESSELLATOR_API ARCH_IMPORT
#   define USDSOLIDTESSELLATOR_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#   define USDSOLIDTESSELLATOR_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#endif

#define USDSOLIDTESSELLATOR_LOCAL ARCH_HIDDEN

#endif // USD_SOLID_TESSELLATOR_API_H
